# Generated by Django 5.2.4 on 2025-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.FloatField(choices=[(1, 'A base de bizcocho tradicional'), (2, 'A base de bizcocho con pistacho'), (3, 'A base de bizcocho de almendra'), (4, 'A base de bizcocho con cafe'), (5, 'Tartas Veganas tipo Loaf'), (6, 'Gluten-free'), (7, 'Brownie'), (8, 'Otros')]),
        ),
    ]
