# Generated by Django 5.2.4 on 2025-07-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
