# Generated by Django 5.2.4 on 2025-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0006_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tartas',
            name='category',
        ),
        migrations.AddField(
            model_name='tartas',
            name='category',
            field=models.ManyToManyField(to='Tartas.category'),
        ),
    ]
