# Generated by Django 5.2.4 on 2025-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
