# Generated by Django 5.2.4 on 2025-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0011_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tartas',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
