# Generated by Django 5.2.4 on 2025-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0016_alter_tartas_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartas',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cart/images/'),
        ),
    ]
