# Generated by Django 5.2.4 on 2025-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0022_remove_category_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartas',
            name='category',
            field=models.ManyToManyField(blank=True, to='Tartas.category'),
        ),
    ]
