# Generated by Django 5.2.4 on 2025-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0023_alter_tartas_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartas',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
