# Generated by Django 5.2.4 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tartas', '0023_alter_tartas_category'),
        ('cart', '0004_order_orderitem_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='ordered_products', to='Tartas.tartas'),
        ),
    ]
